<?php

/**
 * @file
 * Implements some aspects that helps your site to be compliant to the Spanish LOPD Law about personal data management.
 */
use Drupal\Core\Session\AccountProxyInterface;

/**
 * OPERATIONS
 */
define('LOPD_OPERATION_LOGIN', 'login');
define('LOPD_OPERATION_LOGOUT', 'logout');
define('LOPD_OPERATION_LOGIN_FAILED', 'failed_login');

/**
 * Implements hook_permission().
 */
function lopd_permission() {
  return array(
    'config LOPD module' => array(
      'title' => t('Config Spain LOPD module'),
      'description' => t('Allows users to config Spain LOPD module.'),
    ),
    'access LOPD data' => array(
      'title' => t('Access LOPD data'),
      'description' => t('View report of registered events.'),
    ),
  );
}

/**
 * Implements hook_user_login().
 */
function lopd_user_login(AccountProxyInterface $account) {
  lopd_register_operation($account, LOPD_OPERATION_LOGIN);
}

/**
 * Implements hook_user_logout().
 */
function lopd_user_logout(AccountProxyInterface $account) {
  lopd_register_operation($account, LOPD_OPERATION_LOGOUT);
}

/**
 * Login attemps failed.
 */
function lopd_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'user_login':
    case 'user_login_block':
      // Add validation for detect login attempts.
      $form['#validate'][] = 'lopd_login_validate';
      break;
  }
}

/**
 * Check validation for login attemps.
 */
function lopd_login_validate($form, &$form_state) {
  if (empty($form_state['uid'])) {
    $account = db_query("SELECT * FROM {users} WHERE name = :name", array(':name' => $form_state['values']['name']))->fetchObject();
    if ($account) {
      lopd_register_operation($account, LOPD_OPERATION_LOGIN_FAILED);
    }
    else {
      $account['uid'] = 0;
      $account['name'] = $form_state['values']['name'];
      lopd_register_operation((object) $account, LOPD_OPERATION_LOGIN_FAILED);
    }
  }
}

/**
 * Registers an operation.
 *
 * @param AccountProxyInterface $user
 *   An user object.
 * @param type $operation
 *   The operation being registered.
 */
function lopd_register_operation(AccountProxyInterface $user, $operation) {
  $data = array(
    'uid' => $user->id(),
    'authname' => $user->getUsername(),
    'ip' => \Drupal::request()->getClientIp(),
    'operation' => $operation,
    'timestamp' => time(),
  );
  drupal_write_record('lopd', $data);
}

/**
 * Implements hook_views_api().
 */
function lopd_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'lopd') . '/includes/views'
  );
}

/**
 * Implements hook_cron().
 *
 * Remove expired log messages.
 */
function lopd_cron() {
  // Cleanup the lopd table.
  $years = variable_get('lopd_messages_to_keep', 0);
  if ($years > 0 ) {
    db_delete('lopd')
      ->condition('timestamp', strtotime('-' . $years . 'years'), '<')
      ->execute();
  }
}
